### PR TITLE
dosdebug: Test for NULL after moving on

### LINKED ISSUE #653: dosdebug "u" without parameters and without prior "u" crashes dosemu
**Describe the bug**
When starting dosdebug (with dosemu at the DOS command prompt, or with dosemu -H1 it happens too) and entering a "u" command, then dosemu crashes with the following:

```
$ dosemu -H1
ERROR: Fault in dosemu code, in_dpmi=0
ERROR: cpu exception in dosemu code outside of VM86()!
trapno: 0x0e  errorcode: 0x00000004  cr2: 0x00000000
eip: 0xb7d4c566  esp: 0xbfe1aad4  eflags: 0x00010283
cs: 0x0073  ds: 0x007b  es: 0x007b  ss: 0x007b
fs: 0x0000  gs: 0x0033

ERROR: Please install gdb, update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/stsp/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

Terminated with signal 11
$ 
```

dosdebug quits due to this crash:

```
$ dosdebug


DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08

system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
u

Dosemu process ended - quitting
$ 
```

**To Reproduce**
dosemu -H1, in another terminal dosdebug, in dosdebug "u". Compiled dosemu2 from git 990c48c98096

**Expected behavior**
Should disassemble at some default location (cs:ip ?) and not crash.

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2237917/boot.log)

### PR DESCRIPTION
**Pull request by andrewbird**
I did a silly thing here, I tested for NULL at the top of the loop, then
moved on! [fixes #653]

### CODE REVIEW

File: src/tools/debugger/mhpdbgc.c [hunk 1]
```diff
@@ -433,14 +433,14 @@ static int decode_symreg(char *regn, regnum_t *sym, int *typ)
   if (!isalpha(*regn))
     return 0;
 
-  for (n = 0, p = reg_syms[0]; p ; n++) {
-    p = reg_syms[n];
+  for (n = 0, p = reg_syms[0]; p ; /* */) {
```
Comment (stsp) [inline src/tools/debugger/mhpdbgc.c]: Why not `p = reg_syms[++n]` right here
instead of `/* */`?

**Comment by stsp** [comment]
Thanks!
